### ISSUE TITLE
Error while using SystemLocaleDsc module

### ISSUE THREAD

**Issue by ameyaagashe** [PlagueHO/SystemLocaleDsc#19]
Hello Team,

I just imported SystemLocaleDsc module and it is reporting the error as below

[PowerShell] Could not find the module 'SystemLocaleDsc'

Note, I have imported the PSCDesiredStateConfiguration module and whilst I try to import SystemLocaleDsc module I get the error I mentioned above.

Please assist

Thank you.

**Comment by ameyaagashe** [comment]
Ok, I got it. I didn't installed SystemLocaleDSc module hence the error. The error has not gone totally but  a new one has appeared:

The module was installed with the below command
`Install-Module -Name SystemLocaleDsc`

My PowerShell snippet is below:

````
configuration BaselineConfiguration
{
  Import-DSCResource -ModuleName PsDesiredStateConfiguration
  Import-Module -Name SystemLocaleDsc
    node localhost
    {
        WindowsFeature IIS 
        {
            Ensure = "Present"
            Name   = "Web-Server"
        }

        SystemLocale SystemLocaleExample
        {
            IsSingleInstance = 'Yes'
            SystemLocale     = 'en-AU'
        }
      
    }
}
````

The error is Undefined DSC resource 'SystemLocale'. Use import-DscResource to import the resource.

**Comment by PlagueHO** [comment]
I see the issue. Change the line:
```powershell
Import-Module -Name SystemLocaleDsc
```
to:
```powershell
Import-DScResource -Name SystemLocaleDsc
```

That should fix it.

**Comment by ameyaagashe** [comment]
@PlagueHO 
Unfortunately, it is still not working, I am not sure what is the exact issue is, Please find below my script and the error reported.
```
PS C:\OnlyOnMyPC\azure-automation> type .\BaselineConfiguration.ps1
configuration BaselineConfiguration
{
  Import-DSCResource -ModuleName PsDesiredStateConfiguration
  Import-DScResource -Name SystemLocaleDsc
    node localhost
    {
        WindowsFeature IIS
        {
            Ensure = "Present"
            Name   = "Web-Server"
        }

        SystemLocale SystemLocaleExample
        {
            IsSingleInstance = 'Yes'
            SystemLocale     = 'en-AU'
        }

    }
}
PS C:\OnlyOnMyPC\azure-automation> .\BaselineConfiguration.ps1
At C:\OnlyOnMyPC\azure-automation\BaselineConfiguration.ps1:4 char:3
+   Import-DScResource -Name SystemLocaleDsc
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to load resource 'SystemLocaleDsc': Resource not found.
At C:\OnlyOnMyPC\azure-automation\BaselineConfiguration.ps1:13 char:9
+         SystemLocale SystemLocaleExample
+         ~~~~~~~~~~~~
Undefined DSC resource 'SystemLocale'. Use Import-DSCResource to import the resource.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : DscResourcesNotFoundDuringParsing

```

**Comment by johlju** [comment]
It should be `Import-DscResource -ModuleName SystemLocaleDsc`. The parameter `Name` can import specific resource name from several resource modules, while the parameter `ModuelName` imports all resource in one or more modules.
Read more here: https://blogs.msdn.microsoft.com/powershell/2014/04/25/understanding-import-dscresource-keyword-in-desired-state-configuration/

**Comment by PlagueHO** [comment]
Doh! My bad - @johlju is quite right! :grin:

**Comment by ameyaagashe** [comment]
Guys,

Thank you so much for your help! Issue resolved with your recommendation + I need to import them in Shared Modules space in Azure Automation account. I'm hence closing this ticket.

Many thanks once again

Ameya
